name: Publish NPM package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn
      - name: Generate components and dist files [TEMPORARY]
        # run: yarn build
        run: yarn prebuild && yarn build:unpkg
      # - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      # - run: yarn version --minor
      # - run: git push --tags && git push
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - name: Publish package to the NPM registry
        run: npm publish --access public
        # run: |
        #   npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        #   npm config set scope "@florian-lefebvre"
        #   npm config list
        #   npm publish --access public 
        env:
          # CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
          # GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
